package iproject;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LIST_MANAGEMENT.java
 *
 * Created on Nov 17, 2017, 8:32:39 AM
 */


import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author smart11
 */
public class LIST_MANAGEMENT extends javax.swing.JFrame {

    /** Creates new form LIST_MANAGEMENT */
    public LIST_MANAGEMENT() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ShowItems = new javax.swing.JButton();
        ShowOrders = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Delete = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu12 = new javax.swing.JMenu();
        ItemForm = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        OrderForm = new javax.swing.JMenu();
        Menu = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        SearchItemByID = new javax.swing.JMenu();
        SearchOrderByID = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        Exit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM ID", "ITEM NAME", "PRICE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ORDER ID", "DATEOFORD", "AMOUNT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/0484865.gif"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        ShowItems.setFont(new java.awt.Font("Tahoma", 1, 11));
        ShowItems.setText("SHOW ITEMS");
        ShowItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowItemsActionPerformed(evt);
            }
        });

        ShowOrders.setFont(new java.awt.Font("Tahoma", 1, 11));
        ShowOrders.setText("SHOW ORDERS");
        ShowOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowOrdersActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48));
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("      BAKER'S DOZEN");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));

        Delete.setFont(new java.awt.Font("Tahoma", 1, 11));
        Delete.setText("DELETE");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ShowOrders, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                            .addComponent(ShowItems, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(ShowItems)
                        .addGap(18, 18, 18)
                        .addComponent(ShowOrders)
                        .addGap(18, 18, 18)
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jMenu12.setText("ITEM");

        ItemForm.setText("ITEM FORM");
        ItemForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemFormMouseClicked(evt);
            }
        });
        ItemForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemFormActionPerformed(evt);
            }
        });
        jMenu12.add(ItemForm);

        jMenuBar2.add(jMenu12);

        jMenu4.setText("ORDER");

        OrderForm.setText("ORDER FORM");
        OrderForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderFormMouseClicked(evt);
            }
        });
        OrderForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderFormActionPerformed(evt);
            }
        });
        jMenu4.add(OrderForm);

        jMenuBar2.add(jMenu4);

        Menu.setText("MENU");
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClicked(evt);
            }
        });
        jMenuBar2.add(Menu);

        jMenu6.setText("SEARCH");
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        SearchItemByID.setText("ITEM BY ID");
        SearchItemByID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchItemByIDMouseClicked(evt);
            }
        });
        jMenu6.add(SearchItemByID);

        SearchOrderByID.setText("ORDER");
        SearchOrderByID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchOrderByIDMouseClicked(evt);
            }
        });
        jMenu6.add(SearchOrderByID);

        jMenuBar2.add(jMenu6);

        jMenu8.setText("EXIT");

        Exit.setText("CLOSE");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu8.add(Exit);

        jMenuBar2.add(jMenu8);

        jMenu9.setText("ITEM FORM");
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenu3.add(jMenu9);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Connection con;
    Statement st;
    ResultSet rs;
    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
    System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void OrderFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderFormActionPerformed
        
    }//GEN-LAST:event_OrderFormActionPerformed
    
    private void OrderFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderFormMouseClicked
        ORDERS kks = new ORDERS();
            kks.show();
                    this.dispose();
    }//GEN-LAST:event_OrderFormMouseClicked

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
     
    }//GEN-LAST:event_jMenu9MouseClicked


    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed

    }//GEN-LAST:event_jMenu6ActionPerformed

    private void ItemFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemFormActionPerformed

    private void ItemFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemFormMouseClicked
       ITEMS kks = new ITEMS();
            kks.show();
                    this.dispose();
    }//GEN-LAST:event_ItemFormMouseClicked

    private void SearchItemByIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchItemByIDMouseClicked
        DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
        int id=Integer.parseInt(JOptionPane.showInputDialog(null,"ENTER ITEM ID TO SEARCH"));
     try
        {
         while(tm.getRowCount()>0)
         tm.removeRow(0);
         String qry="select * from item where itemid="+id+";";
         rs=st.executeQuery(qry);
          rs.first();
         int price=rs.getInt("price");
         String name=rs.getString("itemname");
         tm.addRow(new Object[]{id,name,price});
          rs.close();
        }
      catch(Exception e)
        {
          JOptionPane.showMessageDialog(null,"RECORD NOT FOUND");
        }
    }//GEN-LAST:event_SearchItemByIDMouseClicked

    private void SearchOrderByIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchOrderByIDMouseClicked
       DefaultTableModel tm=(DefaultTableModel) jTable2.getModel();
       int id=Integer.parseInt(JOptionPane.showInputDialog(null,"ENTER ORDER ID TO SEARCH"));

try
{
    while(tm.getRowCount()>0)
    tm.removeRow(0);
    String qry="select * from orders where orderid="+id+";";
    rs=st.executeQuery(qry);
     while(rs.next()){
     int amt=rs.getInt("amount");
     Date d=rs.getDate("dateoford");
     tm.addRow(new Object[]{id,d,amt});}
     rs.close();
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,"RECORD NOT FOUND");
}
    }//GEN-LAST:event_SearchOrderByIDMouseClicked

    private void ShowItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowItemsActionPerformed
        try
        {
            DefaultTableModel t1=(DefaultTableModel) jTable1.getModel();
            rs=st.executeQuery("select * from item;");
        while
            (rs.next())
            {
            Object row[]={rs.getString(1),rs.getString(2),rs.getString(3)};
            t1.addRow(row);
            }
        }
        catch(Exception e)
        {
          System.out.println(e.toString());
        }
    }//GEN-LAST:event_ShowItemsActionPerformed

    private void ShowOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowOrdersActionPerformed
        try
        {
            DefaultTableModel t2=(DefaultTableModel) jTable2.getModel();
            rs=st.executeQuery("select orderid, datoford,amount from orders;");
          while(rs.next())
            {
              Object row[]={rs.getString(1),rs.getString(2),rs.getString(3)};
              t2.addRow(row);
            }
        }
        catch(Exception e)
        {
          System.out.println(e.toString());
        }
    }//GEN-LAST:event_ShowOrdersActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     try
        {
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/Bakery","root","abc");
            st=con.createStatement();
        }catch(Exception e) {System.out.println(e.toString());}
    
    }//GEN-LAST:event_formWindowOpened

    private void MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseClicked
       MENU kks = new MENU();
            kks.show();
                    this.dispose();
    }//GEN-LAST:event_MenuMouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
       try{
            DefaultTableModel t2=(DefaultTableModel) jTable2.getModel();
            int r=jTable2.getSelectedRow();
            String id=(""+t2.getValueAt(r,0));
            st.executeUpdate("delete from orders where orderid="+id+";");
            t2.removeRow(r);
            
        }
       catch(Exception e)
       {}
    }//GEN-LAST:event_DeleteActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LIST_MANAGEMENT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu ItemForm;
    private javax.swing.JMenu Menu;
    private javax.swing.JMenu OrderForm;
    private javax.swing.JMenu SearchItemByID;
    private javax.swing.JMenu SearchOrderByID;
    private javax.swing.JButton ShowItems;
    private javax.swing.JButton ShowOrders;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

}
